### ISSUE TITLE
Mixin conflict wild Gilded Netherite

### ISSUE THREAD

**Issue by InsaanNotFound** [wutdahack/ActuallyUnbreakingFabric#1]
```
Could not find code source for magic-at:/net/minecraft/class_1886$15.class: java.net.MalformedURLException: unknown protocol: magic-at
[15:36:10] [main/FATAL]: Mixin apply failed gildednetherite.mixins.json:UnbreakingEnchantmentMixin -> net.minecraft.class_1885: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("INVOKE") on net/minecraft/class_1885::shouldPreventDamage with priority 1000 cannot inject into net/minecraft/class_1885::method_8176(Lnet/minecraft/class_1799;ILjava/util/Random;)Z merged by wutdahack.actuallyunbreaking.mixin.UnbreakingEnchantmentMixin with priority 1000 [PREINJECT Applicator Phase -> gildednetherite.mixins.json:UnbreakingEnchantmentMixin -> Prepare Injections ->  -> redirect$dhf000$shouldPreventDamage(Lnet/minecraft/class_1799;)Lnet/minecraft/class_1792; -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_1885::shouldPreventDamage with priority 1000 cannot inject into net/minecraft/class_1885::method_8176(Lnet/minecraft/class_1799;ILjava/util/Random;)Z merged by wutdahack.actuallyunbreaking.mixin.UnbreakingEnchantmentMixin with priority 1000 [PREINJECT Applicator Phase -> gildednetherite.mixins.json:UnbreakingEnchantmentMixin -> Prepare Injections ->  -> redirect$dhf000$shouldPreventDamage(Lnet/minecraft/class_1799;)Lnet/minecraft/class_1792; -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:293) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:375) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1255) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[sponge-mixin-0.9.2+mixin.0.8.2.jar:0.9.2+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) ~[fabric-loader-0.11.2.jar:0.9.2+mixin.0.8.2]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) ~[fabric-loader-0.11.2.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150) ~[fabric-loader-0.11.2.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at net.minecraft.class_2378.method_10243(class_2378.java:156) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at net.minecraft.class_2378.method_29110(class_2378.java:246) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684) ~[?:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:245) ~[intermediary-minecraft-1.16.4-client.jar:?]
	at io.github.cottonmc.jankson.JanksonFactory.builder(JanksonFactory.java:85) ~[2b6556df-af4d-4220-9649-7ec2c9783353.jar:?]
	at io.github.redstoneparadox.paradoxconfig.codec.JanksonConfigCodec.<init>(JanksonConfigCodec.java:18) ~[04c3703e-8299-4397-9fde-b1e9920208e2.jar:?]
	at io.github.redstoneparadox.paradoxconfig.ParadoxConfig.onPreLaunch(ParadoxConfig.java:21) ~[04c3703e-8299-4397-9fde-b1e9920208e2.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) [fabric-loader-0.11.2.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36) [fabric-loader-0.11.2.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:137) [fabric-loader-0.11.2.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'paradoxconfig'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:137)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	... 8 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at net.minecraft.class_2378.method_10243(class_2378.java:156)
	at net.minecraft.class_2378.method_29110(class_2378.java:246)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at net.minecraft.class_2378.<clinit>(class_2378.java:245)
	at io.github.cottonmc.jankson.JanksonFactory.builder(JanksonFactory.java:85)
	at io.github.redstoneparadox.paradoxconfig.codec.JanksonConfigCodec.<init>(JanksonConfigCodec.java:18)
	at io.github.redstoneparadox.paradoxconfig.ParadoxConfig.onPreLaunch(ParadoxConfig.java:21)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	... 11 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [gildednetherite.mixins.json:UnbreakingEnchantmentMixin] from phase [DEFAULT] in config [gildednetherite.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:642)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:594)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356)
	... 25 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/class_1885::shouldPreventDamage with priority 1000 cannot inject into net/minecraft/class_1885::method_8176(Lnet/minecraft/class_1799;ILjava/util/Random;)Z merged by wutdahack.actuallyunbreaking.mixin.UnbreakingEnchantmentMixin with priority 1000 [PREINJECT Applicator Phase -> gildednetherite.mixins.json:UnbreakingEnchantmentMixin -> Prepare Injections ->  -> redirect$dhf000$shouldPreventDamage(Lnet/minecraft/class_1799;)Lnet/minecraft/class_1792; -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:293)
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:375)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1255)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 25 more
Exiting with -1
Process exited with code -1.
```

Gilded Netherite: https://www.curseforge.com/minecraft/mc-mods/gilded-netherite-for-fabric
Both mods interfere with unbreaking.

**Comment by wutdahack** [comment]
i've uploaded a new version to curseforge that should fix this, let me know if it still crashes. (i tested this with the mod and it doesn't crash)
